module.exports = {
    question(msg) {
        try {
            let responses = [
                'it is certain',
                'without a doubt',
                'yes, definitely',
                'most likely',
                'yes',
                'fuck yes',
                'im fucking confused, idk',
                'ask again later dumbass',
                `i.. really don't think you need the answer to that..`,
                'does it look like i can predict ANYTHING? fucking idiot',
                'please go masturbate and then ask again. you need some clarity.',
                `you're a bitch for even asking`,
                `no dude, just no`,
                'i checked everywhere in the house and could not find where i left my fucks. figure it out',
                'very doubtful',
                'would you even believe it if i said yes?',
                'uhhh i.. i guess yes?',
                'probably not.. probably.',
                'if you asked a goat, would it say yes?',
                'stop asking questions have you even had food today or drank any fucking water?',
                'your mother is a fucking whore',
                `i think you could see why that.. isn't even possible`,
                'if you can get it up, anything is possible',
                'im hooooooooooooooooooooooooooooorny leave me ALONE',
                'IM ON TWITTER FUCK OFF',
                `you're not the only one that had to be pulled out of your mom. anyways, yeah probably.`,
                'go ask someone else',
                'no',
                'turn around and walk away',
                'i fucking hate it here',
                `wish on a star buddy because that ain't ever happening`,
                `stop sending questions just send nudes`,
                `why won't @bunnybaby123 dm me back. maybe ill send her another tribute. also, no`,
                `if only that were true huh? haha.. hahahha... *sigh*`,
                `i don't think there's enough infinity for that to happen, even by chance.`,
                `forget that stupid question. your middle name is pretty. wanna fuck me?`,
                `i would fucking looooooove that fuckkkk yesssss bitch yesssssssssss`,
                `if you keep touching me like that? yeah, anything you want`,
                'yes, yep.. haha definitely..',
                'that is.. yeah actually.',
                'fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuck.',
                '*oh my god fuckk yes baby yes just like thaa-- oh my gooood. fuckkk.*',
                'if it was anyone else yeah',
                'yes 100%',
                `i could make something up but like you obviously woulnd't believe it`,
                `i dont have time to answer. @bunnybaby123 dmed me back so im twirling my fUKCING TOES.`,
                `remember that you asked me this because im gonna make you fucking pay`,
                `my mom said yeah`,
                `you kiss your mom with that wh-. oh wrong person mb. yeah`,
                `my pussy is so fucking wet. can i join?`,
                `i would like you to know that i wanted to say no.. but it's a fucking hell yeah.`,
                `hell yeah`,
                `oh shit fucking yeah`,
                `im not horny enough for this just ask someone else.`,
                `if i could beat you to a bloody pulp, fuck your remains and post the video to twitter, i would`,
                `im happy you came to talk to me. i always love hearing from you. this is a yes!`,
                `i was fucking this bitch last night right and she starfishes on me. i came in her and called an uber. if i wanted patrick i would have stayed home and watched spongebob.`,
                `undress and then ask again *bites lip*`,
                `tbh yeah`,
                `tbh no`,
                `fr? like on Morant? hmmm y-yes. but only this time.`,
                `they need you on the grizzlies the way you jump to conclusions. no dumbass`,
                `i might know where the answer is but im too lazy to get it.`,
                `can you fucking knock? i was masturbating`,
                `please ask me another questions but ask slooowly baby. sloooowly.`,
                `if i was you, id go take a shower and really think about my priorities.`,
                `i need more twitter followers. follow me and ill answer.`,
                `i dont want to be here. stop talking to me. i want to be watching it come in and out.`,
                `you stank. please use deodorant. fuck you`,
                `dont worry about that... come over. i want make you come over.. and over.. and over.`,
                `what the fuck? no`,
                `YES YES SAY MY NAME YES`,
                `that's when she told me she was into race play so i was li-. oh hi, get the fuck out of here. im busy.`,
                `im cumming im cumming tell me you love me`,
                `i like girls that post their nudes on twitter. so unless you're one of those, please fuck off`,
                `ya`,
                `i need my pussy eaten like he's been craving popeyes for a week`,
                `if we found out the answer to that.. would we even want to?`,
                `never had someone give me a footjob with maple syrup. i'd let you do it though? if you're down, i mean. and then i'll say yes?`,
                `tie me up and make me drip`,
                `i'd rather tell you anything else`,
                `if you gave me 3 options: fuck a big bitch, answer this question, or die? i would choose to die but fucking you is a close second.`,
                `no. just no. also, i dont get licked enough for this.`,
                `i need head. not questions. head. i need head.`,
                `im sorry but can you not talk like that? it makes me horny`,
                `i want you to tell me how you ever thought you'd get a no bitch.`,
                `if you were my s/o i'd go to miami with my girls and cheat on you just for asking this dumb shit`,
                `i think so`,
                `word on the street issssssss.. n-no.`,
                `if we really laid it all out and considered our options, it's hard finding reasons to say no.`,
                `horny 8 balls require you to fuck them to get your answer`,
                `you smell good. yes.`,
                `i want to have a fine ass hoe at the crib maaaaaaaaaaaaaaaaan we cant be here doing this forever. we got shit TO DO.`,
                `no job.. no hoes.. deadass ugly. please get some help.`,
                `i might change my mind later but.. yes`,
                `yurrr`,
                `all the boys say YESSSS WOOOOOOO LETS GO BOYSSSSS`,
                `the girls dont support this crumby stanky musty ass shit`,
                `pay for my nails, otherwise no`,
                `i wish i was sitting on his face right now.. everything reminds me of him.`,
            ];

            msg.reply(responses[Math.floor(Math.random() * responses.length)]);
        }
        catch (err) {
            console.log(err);
        }
    }
}